# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
linter:
  rules:
    - camel_case_types
