name: sublin_tomp_model
description: Sublin's DTO and classes needed to support TOMP endpoints
version: 1.0.0
# homepage: https://github.com/sublin-maas/sublin_tomp_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.1
  json_serializable: ^4.1.1
  pedantic: ^1.9.0
  test: ^1.14.4
